title: PySty Project Space
theme: minima
highlighter: rouge
markdown: kramdown
plugins:
  - jekyll-seo-tag
show_excerpts: true

badge_root: 'https://img.shields.io/badge/'

active_pages:
  - title: Home
    url: /
    active: true
  - title: PySty
    url: /pysty.html
    active: false
  - title: PySeoa
    url: /pyseoa.html
    active: true
  - title: masemdb
    url: /masemdb.md
    active: false
  - title: About
    url: /about.html
    active: true

# Custom CSS
defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/css/dark-mode.css"