title: MASEM Project Space
theme: minima
plugins:
  - jekyll-seo-tag
show_excerpts: true
header_pages:
  - index.md
  - pysty.md
  - about.md

# Custom CSS
defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/css/dark-mode.css"