title: PySty Project Space
theme: minima
highlighter: rouge
markdown: kramdown
plugins:
  - jekyll-seo-tag
show_excerpts: true

active_pages:
  - title: Home
    url: /
    active: true
  - title: PySty
    url: /pysty.html
    active: true

# Custom CSS
defaults:
  -
    scope:
      path: ""
    values:
      css: "/assets/css/dark-mode.css"